/* eslint-disable import/no-anonymous-default-export */
import React from "react";

import Chart from "@/pesayetu/components/HURUmap/Chart";

export default {
  title: "Components/HURUmap/Chart",
};

const Template = ({ ...args }) => <Chart {...args} />;

export const Default = Template.bind({});

Default.args = {
  title: "Population by Age Group",
  geoCode: "KE",
  indicator: {
    id: 203,
    description:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit habitasse iaculis litora, placerat scelerisque class penatibus purus eget quis sapien id vitae, proin odio velit facilisis volutpat cum luctus curae integer. Ornare dignissim montes donec nostra dui.",
    choropleth_method: "subindicator",
    last_updated_at: "2021-08-04T10:41:20.292118Z",
    metadata: {
      source: "StatsSA Census 2011",
      description: "",
      url: "https://pesayetu.dev.codeforafrica.org",
      licence: {
        name: null,
        url: null,
      },
      primary_group: "age",
      groups: [
        {
          subindicators: [
            "20-24",
            "15-24 (Intl)",
            "15-35 (ZA)",
            "15-19",
            "25-29",
            "30-35",
          ],
          dataset: 241,
          name: "age",
          can_aggregate: false,
          can_filter: true,
        },
        {
          subindicators: ["Female", "Male"],
          dataset: 241,
          name: "gender",
          can_aggregate: true,
          can_filter: true,
        },
        {
          subindicators: [
            "Xitsonga",
            "Sign language",
            "isiNdebele",
            "Setswana",
            "Sesotho",
            "English",
            "Other",
            "Siswati",
            "Afrikaans",
            "Sepedi",
            "Tshivenda",
            "isiXhosa",
            "isiZulu",
          ],
          dataset: 241,
          name: "language",
          can_aggregate: true,
          can_filter: true,
        },
        {
          subindicators: [
            "Black African",
            "Indian or Asian",
            "Other",
            "Coloured",
            "White",
          ],
          dataset: 241,
          name: "race",
          can_aggregate: true,
          can_filter: true,
        },
      ],
    },
    content_type: "indicator",
    dataset_content_type: "quantitative",
    chart_configuration: {
      chart_type: "bar",
      stacked_field: "gender",
      types: {
        Value: {
          formatting: ",.0f",
        },
        Percentage: {
          formatting: ".0%",
          maxX: 1,
          minX: 0,
        },
      },
      filter: {
        defaults: [
          {
            name: "age",
            value: "15-35 (ZA)",
          },
        ],
      },
      defaultType: "Value",
      disableToggle: false,
    },

    data: [
      {
        age: "15-19",
        race: "Black African",
        count: "626.612969999999",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "669.297339999997",
        gender: "Female",
        language: "English",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "141.74499",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "3810.67564000013",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "421.251930000002",
        gender: "Female",
        language: "isiZulu",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "62.6348999999999",
        gender: "Female",
        language: "Other",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "47.71106",
        gender: "Female",
        language: "Sepedi",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "18565.8628299989",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "1612.43719000001",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "332.171440000002",
        gender: "Female",
        language: "Sign language",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "44.9653",
        gender: "Female",
        language: "Siswati",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "36.71208",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "163.609",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "626.626239999999",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "684.579769999997",
        gender: "Male",
        language: "English",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "145.90917",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "3545.93755000012",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "411.476960000002",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "199.79933",
        gender: "Male",
        language: "Other",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "55.9044499999999",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "17683.1090499978",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "1596.22747000001",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "352.152440000002",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "31.35451",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "32.19033",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "15-19",
        race: "Black African",
        count: "278.059310000001",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "447.208600000003",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "26.40005",
        gender: "Female",
        language: "English",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "1.10435",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "5.67795",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "1.10435",
        gender: "Female",
        language: "Sepedi",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "58.7385999999999",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "12.30405",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "1.10435",
        gender: "Female",
        language: "Siswati",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "1.10435",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "1.10435",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "441.920500000003",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "22.1651",
        gender: "Male",
        language: "English",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "2.2087",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "5.52175",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "1.10435",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "1.10435",
        gender: "Male",
        language: "Other",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "1.10435",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "49.64325",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "10.01725",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "2.2868",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "2.2087",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "15-19",
        race: "Coloured",
        count: "3.31305",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "15-19",
        race: "Indian or Asian",
        count: "3.31305",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "15-19",
        race: "Indian or Asian",
        count: "12.14785",
        gender: "Female",
        language: "English",
      },
      {
        age: "15-19",
        race: "Indian or Asian",
        count: "3.31305",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "15-19",
        race: "Indian or Asian",
        count: "11.0435",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "15-19",
        race: "Indian or Asian",
        count: "1.10435",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "15-19",
        race: "Indian or Asian",
        count: "9.93915",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "15-19",
        race: "Indian or Asian",
        count: "32.9218",
        gender: "Male",
        language: "English",
      },
      {
        age: "15-19",
        race: "Indian or Asian",
        count: "10.93915",
        gender: "Male",
        language: "Other",
      },
      {
        age: "15-19",
        race: "Indian or Asian",
        count: "3.31305",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "15-19",
        race: "Indian or Asian",
        count: "1.10435",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "15-19",
        race: "Indian or Asian",
        count: "2.2087",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "15-19",
        race: "Indian or Asian",
        count: "2.2087",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "15-19",
        race: "Indian or Asian",
        count: "1.10435",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "15-19",
        race: "Other",
        count: "6.6261",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "15-19",
        race: "Other",
        count: "2.2087",
        gender: "Female",
        language: "English",
      },
      {
        age: "15-19",
        race: "Other",
        count: "1.10435",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "15-19",
        race: "Other",
        count: "3.31305",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "15-19",
        race: "Other",
        count: "6.6261",
        gender: "Female",
        language: "Other",
      },
      {
        age: "15-19",
        race: "Other",
        count: "7.73045",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "15-19",
        race: "Other",
        count: "2.2087",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "15-19",
        race: "Other",
        count: "1.10435",
        gender: "Female",
        language: "Siswati",
      },
      {
        age: "15-19",
        race: "Other",
        count: "1.10435",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "15-19",
        race: "Other",
        count: "4.31305",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "15-19",
        race: "Other",
        count: "1.10435",
        gender: "Male",
        language: "English",
      },
      {
        age: "15-19",
        race: "Other",
        count: "1.10435",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "15-19",
        race: "Other",
        count: "19.14785",
        gender: "Male",
        language: "Other",
      },
      {
        age: "15-19",
        race: "Other",
        count: "1.10435",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "15-19",
        race: "Other",
        count: "6.52175",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "15-19",
        race: "Other",
        count: "2.2087",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "15-19",
        race: "Other",
        count: "2.2087",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "15-19",
        race: "White",
        count: "1463.97502000001",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "15-19",
        race: "White",
        count: "156.83301",
        gender: "Female",
        language: "English",
      },
      {
        age: "15-19",
        race: "White",
        count: "2.2087",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "15-19",
        race: "White",
        count: "5.4174",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "15-19",
        race: "White",
        count: "4.4174",
        gender: "Female",
        language: "isiZulu",
      },
      {
        age: "15-19",
        race: "White",
        count: "8.8348",
        gender: "Female",
        language: "Other",
      },
      {
        age: "15-19",
        race: "White",
        count: "1.10435",
        gender: "Female",
        language: "Sepedi",
      },
      {
        age: "15-19",
        race: "White",
        count: "17.93813",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "15-19",
        race: "White",
        count: "7.99898",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "15-19",
        race: "White",
        count: "3.31305",
        gender: "Female",
        language: "Sign language",
      },
      {
        age: "15-19",
        race: "White",
        count: "1.10435",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "15-19",
        race: "White",
        count: "1.10435",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "15-19",
        race: "White",
        count: "1460.2715",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "15-19",
        race: "White",
        count: "181.23306",
        gender: "Male",
        language: "English",
      },
      {
        age: "15-19",
        race: "White",
        count: "3.2087",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "15-19",
        race: "White",
        count: "6.79028",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "15-19",
        race: "White",
        count: "6.52175",
        gender: "Male",
        language: "Other",
      },
      {
        age: "15-19",
        race: "White",
        count: "1",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "15-19",
        race: "White",
        count: "40.45784",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "15-19",
        race: "White",
        count: "8.8348",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "15-19",
        race: "White",
        count: "10.20768",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "15-19",
        race: "White",
        count: "1.10435",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "1299.90512",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "1400.64736999999",
        gender: "Female",
        language: "English",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "298.57737",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "7666.64431000026",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "864.380510000005",
        gender: "Female",
        language: "isiZulu",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "177.23408",
        gender: "Female",
        language: "Other",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "113.2559",
        gender: "Female",
        language: "Sepedi",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "38151.461179999",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "3331.59917000002",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "690.951000000004",
        gender: "Female",
        language: "Sign language",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "93.78071",
        gender: "Female",
        language: "Siswati",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "76.42416",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "356.09528",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "1270.96471",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "1394.23161999999",
        gender: "Male",
        language: "English",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "319.23268",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "7382.59653000024",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "942.388290000004",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "641.529510000003",
        gender: "Male",
        language: "Other",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "141.38742",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "35313.7651999957",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "3203.21842000002",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "646.669980000003",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "67.85789",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "104.71986",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "15-24 (Intl)",
        race: "Black African",
        count: "583.995900000002",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "858.494100000005",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "46.27835",
        gender: "Female",
        language: "English",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "2.2087",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "12.2778",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "1.10435",
        gender: "Female",
        language: "Other",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "2.2087",
        gender: "Female",
        language: "Sepedi",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "116.1904",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "33.7553",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "2.2087",
        gender: "Female",
        language: "Siswati",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "2.2087",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "1.10435",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "896.952300000006",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "45.35645",
        gender: "Male",
        language: "English",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "2.2087",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "10.01725",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "2.2087",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "3.31305",
        gender: "Male",
        language: "Other",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "3.31305",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "103.782",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "14.43465",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "4.39115",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "2.2087",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "2.2087",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "15-24 (Intl)",
        race: "Coloured",
        count: "5.52175",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "15-24 (Intl)",
        race: "Indian or Asian",
        count: "9.8348",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "15-24 (Intl)",
        race: "Indian or Asian",
        count: "35.23485",
        gender: "Female",
        language: "English",
      },
      {
        age: "15-24 (Intl)",
        race: "Indian or Asian",
        count: "1",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "15-24 (Intl)",
        race: "Indian or Asian",
        count: "4.4174",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "15-24 (Intl)",
        race: "Indian or Asian",
        count: "8.4174",
        gender: "Female",
        language: "Other",
      },
      {
        age: "15-24 (Intl)",
        race: "Indian or Asian",
        count: "14.35655",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "15-24 (Intl)",
        race: "Indian or Asian",
        count: "3.31305",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "15-24 (Intl)",
        race: "Indian or Asian",
        count: "1.10435",
        gender: "Female",
        language: "Siswati",
      },
      {
        age: "15-24 (Intl)",
        race: "Indian or Asian",
        count: "1.10435",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "15-24 (Intl)",
        race: "Indian or Asian",
        count: "18.6696",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "15-24 (Intl)",
        race: "Indian or Asian",
        count: "91.4523499999999",
        gender: "Male",
        language: "English",
      },
      {
        age: "15-24 (Intl)",
        race: "Indian or Asian",
        count: "3.2087",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "15-24 (Intl)",
        race: "Indian or Asian",
        count: "1.10435",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "15-24 (Intl)",
        race: "Indian or Asian",
        count: "129.4785",
        gender: "Male",
        language: "Other",
      },
      {
        age: "15-24 (Intl)",
        race: "Indian or Asian",
        count: "14.35655",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "15-24 (Intl)",
        race: "Indian or Asian",
        count: "1.10435",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "15-24 (Intl)",
        race: "Indian or Asian",
        count: "4.4174",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "15-24 (Intl)",
        race: "Indian or Asian",
        count: "3.31305",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "15-24 (Intl)",
        race: "Indian or Asian",
        count: "1.10435",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "12.0435",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "6.52175",
        gender: "Female",
        language: "English",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "1.10435",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "6.6261",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "23.98265",
        gender: "Female",
        language: "Other",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "16.56525",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "2.2087",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "1.10435",
        gender: "Female",
        language: "Siswati",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "3.31305",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "6.52175",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "33.1305",
        gender: "Male",
        language: "English",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "3.2087",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "2.2087",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "105.1393",
        gender: "Male",
        language: "Other",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "1.10435",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "13.14785",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "1.10435",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "1.10435",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "2.2087",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "15-24 (Intl)",
        race: "Other",
        count: "10.93915",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "2782.14750000001",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "279.86388",
        gender: "Female",
        language: "English",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "4.4174",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "9.8348",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "5.52175",
        gender: "Female",
        language: "isiZulu",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "11.31203",
        gender: "Female",
        language: "Other",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "1.10435",
        gender: "Female",
        language: "Sepedi",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "59.06761",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "11.31203",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "5.52175",
        gender: "Female",
        language: "Sign language",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "1.10435",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "2.2087",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "2761.2783",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "284.90738",
        gender: "Male",
        language: "English",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "5.4174",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "8.99898",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "1.10435",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "14.2522",
        gender: "Male",
        language: "Other",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "2",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "76.60263",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "16.53502",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "14.62508",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "2.2087",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "2.2087",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "15-24 (Intl)",
        race: "White",
        count: "1.10435",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "2438.33582",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "2615.33224999999",
        gender: "Female",
        language: "English",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "561.29277",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "14062.7617000005",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "1546.48548000001",
        gender: "Female",
        language: "isiZulu",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "453.87701",
        gender: "Female",
        language: "Other",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "249.88264",
        gender: "Female",
        language: "Sepedi",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "72448.1163899937",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "6354.88046000004",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "1301.77636000001",
        gender: "Female",
        language: "Sign language",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "171.93634",
        gender: "Female",
        language: "Siswati",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "148.5951",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "752.7266",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "2252.32221",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "2509.21131999999",
        gender: "Male",
        language: "English",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "592.84373",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "13476.4698400004",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "1834.39835000001",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "1420.74724000001",
        gender: "Male",
        language: "Other",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "321.41421",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "65822.4473799897",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "6121.98223000002",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "1167.81961000001",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "150.01352",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "214.18548",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "15-35 (ZA)",
        race: "Black African",
        count: "1260.25484000001",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "1643.39690000001",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "103.49585",
        gender: "Female",
        language: "English",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "5.52175",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "18.9039",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "2.2087",
        gender: "Female",
        language: "isiZulu",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "3.31305",
        gender: "Female",
        language: "Other",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "2.2087",
        gender: "Female",
        language: "Sepedi",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "215.1901",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "54.99785",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "2.2087",
        gender: "Female",
        language: "Sign language",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "3.31305",
        gender: "Female",
        language: "Siswati",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "4.5736",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "1.10435",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "1664.06890000001",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "79.5913",
        gender: "Male",
        language: "English",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "2.2087",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "15.6171",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "4.4174",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "6.52175",
        gender: "Male",
        language: "Other",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "5.52175",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "183.29455",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "33.72905",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "6.59985",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "2.2087",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "2.2087",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "15-35 (ZA)",
        race: "Coloured",
        count: "5.52175",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "15.2522",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "71.57405",
        gender: "Female",
        language: "English",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "1",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "6.6261",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "1",
        gender: "Female",
        language: "isiZulu",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "40.60875",
        gender: "Female",
        language: "Other",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "24.19135",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "3.31305",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "3.31305",
        gender: "Female",
        language: "Sign language",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "3.31305",
        gender: "Female",
        language: "Siswati",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "1.10435",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "1.10435",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "31.9218",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "299.5484",
        gender: "Male",
        language: "English",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "12.0435",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "4.4174",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "1",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "476.9487",
        gender: "Male",
        language: "Other",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "46.174",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "4.4174",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "4.4174",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "6.4174",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "3.31305",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "15-35 (ZA)",
        race: "Indian or Asian",
        count: "4.2087",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "20.77395",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "17.2522",
        gender: "Female",
        language: "English",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "4.31305",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "6.6261",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "2.2087",
        gender: "Female",
        language: "isiZulu",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "62.8001",
        gender: "Female",
        language: "Other",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "29.81745",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "2.2087",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "2.2087",
        gender: "Female",
        language: "Siswati",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "1.10435",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "7.73045",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "21.8783",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "82.5132",
        gender: "Male",
        language: "English",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "4.31305",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "4.31305",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "1.10435",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "337.8006",
        gender: "Male",
        language: "Other",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "1.10435",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "35.23485",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "2.2087",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "4.4174",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "5.4174",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "15-35 (ZA)",
        race: "Other",
        count: "31.81745",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "6011.30900000003",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "568.63566",
        gender: "Female",
        language: "English",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "7.73045",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "25.83276",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "8.8348",
        gender: "Female",
        language: "isiZulu",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "23.45988",
        gender: "Female",
        language: "Other",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "1.10435",
        gender: "Female",
        language: "Sepedi",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "145.93775",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "24.83276",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "11.0435",
        gender: "Female",
        language: "Sign language",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "4.68593",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "3.31305",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "5773.10584000001",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "561.12985",
        gender: "Male",
        language: "English",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "8.73045",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "22.51971",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "12.14785",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "27.5044",
        gender: "Male",
        language: "Other",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "3.10435",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "146.90752",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "38.48744",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "24.72841",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "4.4174",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "3.31305",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "15-35 (ZA)",
        race: "White",
        count: "2.2087",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "673.292149999998",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "731.350029999995",
        gender: "Female",
        language: "English",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "156.83238",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "3855.96867000013",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "443.128580000003",
        gender: "Female",
        language: "isiZulu",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "114.59918",
        gender: "Female",
        language: "Other",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "65.5448399999999",
        gender: "Female",
        language: "Sepedi",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "19585.5983500001",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "1719.16198000001",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "358.779560000002",
        gender: "Female",
        language: "Sign language",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "48.81541",
        gender: "Female",
        language: "Siswati",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "39.71208",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "192.48628",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "644.338469999999",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "709.651849999996",
        gender: "Male",
        language: "English",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "173.32351",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "3836.65898000012",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "530.911330000002",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "441.730180000003",
        gender: "Male",
        language: "Other",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "85.4829699999999",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "17630.6561499979",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "1606.99095000001",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "294.517540000001",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "36.50338",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "72.5295299999999",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "20-24",
        race: "Black African",
        count: "305.936590000001",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "411.285500000002",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "19.8783",
        gender: "Female",
        language: "English",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "1.10435",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "6.59985",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "1.10435",
        gender: "Female",
        language: "Other",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "1.10435",
        gender: "Female",
        language: "Sepedi",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "57.4517999999999",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "21.45125",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "1.10435",
        gender: "Female",
        language: "Siswati",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "1.10435",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "455.031800000003",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "23.19135",
        gender: "Male",
        language: "English",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "4.4955",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "1.10435",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "2.2087",
        gender: "Male",
        language: "Other",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "2.2087",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "54.1387499999999",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "4.4174",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "2.10435",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "2.2087",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "20-24",
        race: "Coloured",
        count: "2.2087",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "20-24",
        race: "Indian or Asian",
        count: "6.52175",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "20-24",
        race: "Indian or Asian",
        count: "23.087",
        gender: "Female",
        language: "English",
      },
      {
        age: "20-24",
        race: "Indian or Asian",
        count: "1",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "20-24",
        race: "Indian or Asian",
        count: "1.10435",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "20-24",
        race: "Indian or Asian",
        count: "8.4174",
        gender: "Female",
        language: "Other",
      },
      {
        age: "20-24",
        race: "Indian or Asian",
        count: "3.31305",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "20-24",
        race: "Indian or Asian",
        count: "2.2087",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "20-24",
        race: "Indian or Asian",
        count: "1.10435",
        gender: "Female",
        language: "Siswati",
      },
      {
        age: "20-24",
        race: "Indian or Asian",
        count: "1.10435",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "20-24",
        race: "Indian or Asian",
        count: "8.73045",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "20-24",
        race: "Indian or Asian",
        count: "58.5305499999999",
        gender: "Male",
        language: "English",
      },
      {
        age: "20-24",
        race: "Indian or Asian",
        count: "3.2087",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "20-24",
        race: "Indian or Asian",
        count: "1.10435",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "20-24",
        race: "Indian or Asian",
        count: "118.53935",
        gender: "Male",
        language: "Other",
      },
      {
        age: "20-24",
        race: "Indian or Asian",
        count: "11.0435",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "20-24",
        race: "Indian or Asian",
        count: "2.2087",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "20-24",
        race: "Indian or Asian",
        count: "1.10435",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "20-24",
        race: "Other",
        count: "5.4174",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "20-24",
        race: "Other",
        count: "4.31305",
        gender: "Female",
        language: "English",
      },
      {
        age: "20-24",
        race: "Other",
        count: "3.31305",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "20-24",
        race: "Other",
        count: "17.35655",
        gender: "Female",
        language: "Other",
      },
      {
        age: "20-24",
        race: "Other",
        count: "8.8348",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "20-24",
        race: "Other",
        count: "2.2087",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "20-24",
        race: "Other",
        count: "2.2087",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "20-24",
        race: "Other",
        count: "32.02615",
        gender: "Male",
        language: "English",
      },
      {
        age: "20-24",
        race: "Other",
        count: "3.2087",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "20-24",
        race: "Other",
        count: "1.10435",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "20-24",
        race: "Other",
        count: "85.9914499999999",
        gender: "Male",
        language: "Other",
      },
      {
        age: "20-24",
        race: "Other",
        count: "6.6261",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "20-24",
        race: "Other",
        count: "1.10435",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "20-24",
        race: "Other",
        count: "1.10435",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "20-24",
        race: "Other",
        count: "8.73045",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "20-24",
        race: "White",
        count: "1318.17248",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "20-24",
        race: "White",
        count: "123.03087",
        gender: "Female",
        language: "English",
      },
      {
        age: "20-24",
        race: "White",
        count: "2.2087",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "20-24",
        race: "White",
        count: "4.4174",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "20-24",
        race: "White",
        count: "1.10435",
        gender: "Female",
        language: "isiZulu",
      },
      {
        age: "20-24",
        race: "White",
        count: "2.47723",
        gender: "Female",
        language: "Other",
      },
      {
        age: "20-24",
        race: "White",
        count: "41.12948",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "20-24",
        race: "White",
        count: "3.31305",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "20-24",
        race: "White",
        count: "2.2087",
        gender: "Female",
        language: "Sign language",
      },
      {
        age: "20-24",
        race: "White",
        count: "1.10435",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "20-24",
        race: "White",
        count: "1301.0068",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "20-24",
        race: "White",
        count: "103.67432",
        gender: "Male",
        language: "English",
      },
      {
        age: "20-24",
        race: "White",
        count: "2.2087",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "20-24",
        race: "White",
        count: "2.2087",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "20-24",
        race: "White",
        count: "1.10435",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "20-24",
        race: "White",
        count: "7.73045",
        gender: "Male",
        language: "Other",
      },
      {
        age: "20-24",
        race: "White",
        count: "1",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "20-24",
        race: "White",
        count: "36.14479",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "20-24",
        race: "White",
        count: "7.70022",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "20-24",
        race: "White",
        count: "4.4174",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "20-24",
        race: "White",
        count: "2.2087",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "20-24",
        race: "White",
        count: "2.2087",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "581.870030000001",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "632.137629999999",
        gender: "Female",
        language: "English",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "129.67126",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "3355.0883500001",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "347.604150000002",
        gender: "Female",
        language: "isiZulu",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "147.79053",
        gender: "Female",
        language: "Other",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "79.7222899999999",
        gender: "Female",
        language: "Sepedi",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "17633.8114799979",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "1523.65411000001",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "313.829570000001",
        gender: "Female",
        language: "Sign language",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "42.12948",
        gender: "Female",
        language: "Siswati",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "41.65225",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "200.33741",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "488.417050000003",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "632.019379999999",
        gender: "Male",
        language: "English",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "120.94183",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "3201.07168000009",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "442.238030000002",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "426.686680000002",
        gender: "Male",
        language: "Other",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "92.1253999999999",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "15754.9733699968",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "1418.58122",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "257.418290000001",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "41.92078",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "67.6491899999999",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "25-29",
        race: "Black African",
        count: "332.562690000001",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "25-29",
        race: "Coloured",
        count: "414.077450000002",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "25-29",
        race: "Coloured",
        count: "24.2957",
        gender: "Female",
        language: "English",
      },
      {
        age: "25-29",
        race: "Coloured",
        count: "3.31305",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "25-29",
        race: "Coloured",
        count: "1.10435",
        gender: "Female",
        language: "Other",
      },
      {
        age: "25-29",
        race: "Coloured",
        count: "48.35645",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "25-29",
        race: "Coloured",
        count: "13.53835",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "25-29",
        race: "Coloured",
        count: "1.10435",
        gender: "Female",
        language: "Sign language",
      },
      {
        age: "25-29",
        race: "Coloured",
        count: "2.3649",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "25-29",
        race: "Coloured",
        count: "364.110200000002",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "25-29",
        race: "Coloured",
        count: "15.4609",
        gender: "Male",
        language: "English",
      },
      {
        age: "25-29",
        race: "Coloured",
        count: "5.59985",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "25-29",
        race: "Coloured",
        count: "1.10435",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "25-29",
        race: "Coloured",
        count: "2.10435",
        gender: "Male",
        language: "Other",
      },
      {
        age: "25-29",
        race: "Coloured",
        count: "1.10435",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "25-29",
        race: "Coloured",
        count: "34.31295",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "25-29",
        race: "Coloured",
        count: "9.0691",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "25-29",
        race: "Coloured",
        count: "2.2087",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "25-29",
        race: "Indian or Asian",
        count: "2.10435",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "25-29",
        race: "Indian or Asian",
        count: "15.4609",
        gender: "Female",
        language: "English",
      },
      {
        age: "25-29",
        race: "Indian or Asian",
        count: "1",
        gender: "Female",
        language: "isiZulu",
      },
      {
        age: "25-29",
        race: "Indian or Asian",
        count: "13.8348",
        gender: "Female",
        language: "Other",
      },
      {
        age: "25-29",
        race: "Indian or Asian",
        count: "4.4174",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "25-29",
        race: "Indian or Asian",
        count: "2.2087",
        gender: "Female",
        language: "Sign language",
      },
      {
        age: "25-29",
        race: "Indian or Asian",
        count: "8.8348",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "25-29",
        race: "Indian or Asian",
        count: "111.435",
        gender: "Male",
        language: "English",
      },
      {
        age: "25-29",
        race: "Indian or Asian",
        count: "5.52175",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "25-29",
        race: "Indian or Asian",
        count: "2.2087",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "25-29",
        race: "Indian or Asian",
        count: "181.96555",
        gender: "Male",
        language: "Other",
      },
      {
        age: "25-29",
        race: "Indian or Asian",
        count: "21.98265",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "25-29",
        race: "Indian or Asian",
        count: "2.2087",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "25-29",
        race: "Indian or Asian",
        count: "4.31305",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "25-29",
        race: "Indian or Asian",
        count: "2.10435",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "25-29",
        race: "Other",
        count: "2.2087",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "25-29",
        race: "Other",
        count: "5.2087",
        gender: "Female",
        language: "English",
      },
      {
        age: "25-29",
        race: "Other",
        count: "1.10435",
        gender: "Female",
        language: "isiZulu",
      },
      {
        age: "25-29",
        race: "Other",
        count: "22.56525",
        gender: "Female",
        language: "Other",
      },
      {
        age: "25-29",
        race: "Other",
        count: "9.93915",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "25-29",
        race: "Other",
        count: "1.10435",
        gender: "Female",
        language: "Siswati",
      },
      {
        age: "25-29",
        race: "Other",
        count: "1.10435",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "25-29",
        race: "Other",
        count: "3.31305",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "25-29",
        race: "Other",
        count: "8.73045",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "25-29",
        race: "Other",
        count: "34.02615",
        gender: "Male",
        language: "English",
      },
      {
        age: "25-29",
        race: "Other",
        count: "1.10435",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "25-29",
        race: "Other",
        count: "1",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "25-29",
        race: "Other",
        count: "1.10435",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "25-29",
        race: "Other",
        count: "121.95675",
        gender: "Male",
        language: "Other",
      },
      {
        age: "25-29",
        race: "Other",
        count: "11.0435",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "25-29",
        race: "Other",
        count: "2.2087",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "25-29",
        race: "Other",
        count: "14.2522",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "25-29",
        race: "White",
        count: "1398.04151",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "25-29",
        race: "White",
        count: "117.86669",
        gender: "Female",
        language: "English",
      },
      {
        age: "25-29",
        race: "White",
        count: "2.2087",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "25-29",
        race: "White",
        count: "11.58056",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "25-29",
        race: "White",
        count: "4.4174",
        gender: "Female",
        language: "Other",
      },
      {
        age: "25-29",
        race: "White",
        count: "37.41332",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "25-29",
        race: "White",
        count: "6.6261",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "25-29",
        race: "White",
        count: "3.31305",
        gender: "Female",
        language: "Sign language",
      },
      {
        age: "25-29",
        race: "White",
        count: "3.58158",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "25-29",
        race: "White",
        count: "1396.78727",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "25-29",
        race: "White",
        count: "133.16443",
        gender: "Male",
        language: "English",
      },
      {
        age: "25-29",
        race: "White",
        count: "1.10435",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "25-29",
        race: "White",
        count: "3.31305",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "25-29",
        race: "White",
        count: "7.73045",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "25-29",
        race: "White",
        count: "5.52175",
        gender: "Male",
        language: "Other",
      },
      {
        age: "25-29",
        race: "White",
        count: "1.10435",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "25-29",
        race: "White",
        count: "38.51767",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "25-29",
        race: "White",
        count: "11.47621",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "25-29",
        race: "White",
        count: "3.31305",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "25-29",
        race: "White",
        count: "1.10435",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "25-29",
        race: "White",
        count: "1.10435",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "556.560670000002",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "582.547250000001",
        gender: "Female",
        language: "English",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "133.04414",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "3041.02904000009",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "334.500820000002",
        gender: "Female",
        language: "isiZulu",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "128.8524",
        gender: "Female",
        language: "Other",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "56.9044499999999",
        gender: "Female",
        language: "Sepedi",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "16662.8437299968",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "1499.62718000001",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "296.995790000001",
        gender: "Female",
        language: "Sign language",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "36.02615",
        gender: "Female",
        language: "Siswati",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "30.51869",
        gender: "Female",
        language: "Tshivenda",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "196.29391",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "492.940450000003",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "482.960320000003",
        gender: "Male",
        language: "English",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "152.66922",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "2892.80163000008",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "449.772030000003",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "352.531050000002",
        gender: "Male",
        language: "Other",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "87.9013899999999",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "14753.7088099972",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "1500.18259",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "263.731340000001",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "40.23485",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "41.81643",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "30-35",
        race: "Black African",
        count: "343.696250000002",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "30-35",
        race: "Coloured",
        count: "370.825350000002",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "30-35",
        race: "Coloured",
        count: "32.9218",
        gender: "Female",
        language: "English",
      },
      {
        age: "30-35",
        race: "Coloured",
        count: "3.31305",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "30-35",
        race: "Coloured",
        count: "3.31305",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "30-35",
        race: "Coloured",
        count: "2.2087",
        gender: "Female",
        language: "isiZulu",
      },
      {
        age: "30-35",
        race: "Coloured",
        count: "1.10435",
        gender: "Female",
        language: "Other",
      },
      {
        age: "30-35",
        race: "Coloured",
        count: "50.64325",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "30-35",
        race: "Coloured",
        count: "7.7042",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "30-35",
        race: "Coloured",
        count: "1.10435",
        gender: "Female",
        language: "Sign language",
      },
      {
        age: "30-35",
        race: "Coloured",
        count: "1.10435",
        gender: "Female",
        language: "Siswati",
      },
      {
        age: "30-35",
        race: "Coloured",
        count: "403.006400000002",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "30-35",
        race: "Coloured",
        count: "18.77395",
        gender: "Male",
        language: "English",
      },
      {
        age: "30-35",
        race: "Coloured",
        count: "1.10435",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "30-35",
        race: "Coloured",
        count: "1.10435",
        gender: "Male",
        language: "Other",
      },
      {
        age: "30-35",
        race: "Coloured",
        count: "1.10435",
        gender: "Male",
        language: "Sepedi",
      },
      {
        age: "30-35",
        race: "Coloured",
        count: "45.1996",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "30-35",
        race: "Coloured",
        count: "10.2253",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "30-35",
        race: "Indian or Asian",
        count: "3.31305",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "30-35",
        race: "Indian or Asian",
        count: "20.8783",
        gender: "Female",
        language: "English",
      },
      {
        age: "30-35",
        race: "Indian or Asian",
        count: "2.2087",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "30-35",
        race: "Indian or Asian",
        count: "18.35655",
        gender: "Female",
        language: "Other",
      },
      {
        age: "30-35",
        race: "Indian or Asian",
        count: "5.4174",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "30-35",
        race: "Indian or Asian",
        count: "1.10435",
        gender: "Female",
        language: "Sign language",
      },
      {
        age: "30-35",
        race: "Indian or Asian",
        count: "2.2087",
        gender: "Female",
        language: "Siswati",
      },
      {
        age: "30-35",
        race: "Indian or Asian",
        count: "1.10435",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "30-35",
        race: "Indian or Asian",
        count: "4.4174",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "30-35",
        race: "Indian or Asian",
        count: "96.6610499999998",
        gender: "Male",
        language: "English",
      },
      {
        age: "30-35",
        race: "Indian or Asian",
        count: "3.31305",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "30-35",
        race: "Indian or Asian",
        count: "1.10435",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "30-35",
        race: "Indian or Asian",
        count: "1",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "30-35",
        race: "Indian or Asian",
        count: "165.50465",
        gender: "Male",
        language: "Other",
      },
      {
        age: "30-35",
        race: "Indian or Asian",
        count: "9.8348",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "30-35",
        race: "Indian or Asian",
        count: "1.10435",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "30-35",
        race: "Indian or Asian",
        count: "2.10435",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "30-35",
        race: "Indian or Asian",
        count: "1",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "30-35",
        race: "Other",
        count: "6.52175",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "30-35",
        race: "Other",
        count: "5.52175",
        gender: "Female",
        language: "English",
      },
      {
        age: "30-35",
        race: "Other",
        count: "3.2087",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "30-35",
        race: "Other",
        count: "1.10435",
        gender: "Female",
        language: "isiZulu",
      },
      {
        age: "30-35",
        race: "Other",
        count: "16.2522",
        gender: "Female",
        language: "Other",
      },
      {
        age: "30-35",
        race: "Other",
        count: "3.31305",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "30-35",
        race: "Other",
        count: "1.10435",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "30-35",
        race: "Other",
        count: "6.6261",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "30-35",
        race: "Other",
        count: "15.35655",
        gender: "Male",
        language: "English",
      },
      {
        age: "30-35",
        race: "Other",
        count: "1.10435",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "30-35",
        race: "Other",
        count: "110.70455",
        gender: "Male",
        language: "Other",
      },
      {
        age: "30-35",
        race: "Other",
        count: "11.0435",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "30-35",
        race: "Other",
        count: "1.10435",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "30-35",
        race: "Other",
        count: "3.31305",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "30-35",
        race: "Other",
        count: "1",
        gender: "Male",
        language: "Tshivenda",
      },
      {
        age: "30-35",
        race: "Other",
        count: "6.6261",
        gender: "Male",
        language: "Xitsonga",
      },
      {
        age: "30-35",
        race: "White",
        count: "1831.11999000002",
        gender: "Female",
        language: "Afrikaans",
      },
      {
        age: "30-35",
        race: "White",
        count: "170.90509",
        gender: "Female",
        language: "English",
      },
      {
        age: "30-35",
        race: "White",
        count: "1.10435",
        gender: "Female",
        language: "isiNdebele",
      },
      {
        age: "30-35",
        race: "White",
        count: "4.4174",
        gender: "Female",
        language: "isiXhosa",
      },
      {
        age: "30-35",
        race: "White",
        count: "3.31305",
        gender: "Female",
        language: "isiZulu",
      },
      {
        age: "30-35",
        race: "White",
        count: "7.73045",
        gender: "Female",
        language: "Other",
      },
      {
        age: "30-35",
        race: "White",
        count: "49.45682",
        gender: "Female",
        language: "Sesotho",
      },
      {
        age: "30-35",
        race: "White",
        count: "6.89463",
        gender: "Female",
        language: "Setswana",
      },
      {
        age: "30-35",
        race: "White",
        count: "2.2087",
        gender: "Female",
        language: "Sign language",
      },
      {
        age: "30-35",
        race: "White",
        count: "1.10435",
        gender: "Female",
        language: "Xitsonga",
      },
      {
        age: "30-35",
        race: "White",
        count: "1615.04027000001",
        gender: "Male",
        language: "Afrikaans",
      },
      {
        age: "30-35",
        race: "White",
        count: "143.05804",
        gender: "Male",
        language: "English",
      },
      {
        age: "30-35",
        race: "White",
        count: "2.2087",
        gender: "Male",
        language: "isiNdebele",
      },
      {
        age: "30-35",
        race: "White",
        count: "10.20768",
        gender: "Male",
        language: "isiXhosa",
      },
      {
        age: "30-35",
        race: "White",
        count: "3.31305",
        gender: "Male",
        language: "isiZulu",
      },
      {
        age: "30-35",
        race: "White",
        count: "7.73045",
        gender: "Male",
        language: "Other",
      },
      {
        age: "30-35",
        race: "White",
        count: "31.78722",
        gender: "Male",
        language: "Sesotho",
      },
      {
        age: "30-35",
        race: "White",
        count: "10.47621",
        gender: "Male",
        language: "Setswana",
      },
      {
        age: "30-35",
        race: "White",
        count: "6.79028",
        gender: "Male",
        language: "Sign language",
      },
      {
        age: "30-35",
        race: "White",
        count: "1.10435",
        gender: "Male",
        language: "Siswati",
      },
      {
        age: "30-35",
        race: "White",
        count: "1.10435",
        gender: "Male",
        language: "Tshivenda",
      },
    ],
  },
};
